// Generated by GG/scripts/sync-game-menus.mjs.
export const GAME_MENU = {
  "selector": "[data-gg-pregame]",
  "steps": {
    "en": [
      "Guess the secret word from associations. Each player takes a turn as host.",
      "As host, reveal the next clue. As a guesser, type your answer before another player gets it.",
      "Guessing with fewer clues earns more points for the guesser and host. The highest score after all rounds wins."
    ],
    "ru": [
      "Угадывай секретное слово по ассоциациям. Каждый игрок по очереди становится ведущим.",
      "Ведущий открывает следующую подсказку. Остальные вводят догадки, стараясь ответить первыми.",
      "Чем меньше подсказок, тем больше очков получают угадавший и ведущий. Побеждает лучший счёт за все раунды."
    ]
  }
}
