// English translations keyed by the exact Russian source string.
// Russian stays the default language; these are used when the app runs in EN.
export const EN: Record<string, string> = {
  // --- brand / tagline ---
  'Крокоша': 'Croaky',
  'Угадывай слова по подсказкам': 'Guess words from clues',
  'Загадываем слово': 'Thinking of a word',
  'Намекай, угадывай и набирай очки': 'Give hints, guess and score points',

  // --- difficulty picker (App.tsx) ---
  'Легко': 'Easy',
  'Спокойная партия': 'A relaxed game',
  'Средне': 'Medium',
  'Достойные соперники': 'Worthy opponents',
  'Сложно': 'Hard',
  'Безжалостные боты': 'Ruthless bots',
  'Выбери сложность': 'Choose a difficulty',
  'Так будут играть боты, что займут пустые места': 'This is how the bots filling empty seats will play',
  'Насколько сообразительны боты': 'How sharp the bots are',

  // --- result modal (App.tsx) ---
  'Ты победил!': 'You won!',
  'Победил ': 'Winner: ',
  'Твой счёт: ': 'Your score: ',
  'В следующий раз повезёт!': 'Better luck next time!',
  'Ты': 'You',
  ' монет': ' coins',
  'В меню': 'Menu',
  'Играть ещё 🐊': 'Play again 🐊',
  'Домой': 'Home',

  // --- Home.tsx ---
  'Победы': 'Wins',
  'Серия': 'Streak',
  'Монеты': 'Coins',
  'Одиночная игра': 'Single player',
  'Против ботов, выбери сложность': 'Play against bots, pick a difficulty',
  'Быстрая игра': 'Quick match',
  'Случайные соперники онлайн': 'Random opponents online',
  'Игра с друзьями': 'Play with friends',
  'Создай комнату и поделись кодом': 'Create a room and share the code',
  'Войти по коду': 'Join by code',
  'Введи код из 4 символов': 'Enter a 4-character code',
  'Рейтинг': 'Leaderboard',
  'Правила': 'Rules',

  // --- Lobby.tsx ---
  'Назад': 'Back',
  'КОД': 'CODE',
  'Войти в комнату': 'Join room',
  'Ищем соперников': 'Finding opponents',
  'Подбираем игроков. Партия начнётся сама через пару секунд.': 'Matching players. The game will start on its own in a few seconds.',
  'Отмена': 'Cancel',
  'Комната': 'Room',
  'Код комнаты': 'Room code',
  'Поделись кодом с друзьями. Пустые места займут боты.': 'Share the code with friends. Empty seats are filled by bots.',
  'Пригласить друзей 📨': 'Invite friends 📨',
  'Заходи в «': 'Join me in “',
  '»! Код комнаты: ': '”! Room code: ',
  'Хост': 'Host',
  'Бот': 'Bot',
  'Готов': 'Ready',
  'Начать игру 🐊': 'Start game 🐊',
  'Ждём, пока хост начнёт игру': 'Waiting for the host to start the game',

  // --- Rules.tsx ---
  'Как играть': 'How to play',
  'Один ведущий за раунд': 'One host per round',
  'Каждый раунд один игрок становится ведущим и получает тайное слово. По очереди им будут все.': 'Each round one player becomes the host and gets a secret word. Everyone takes a turn.',
  'Подсказки по одной': 'Hints one at a time',
  'Ведущий открывает ассоциации к слову по одной. Чем меньше подсказок, тем ценнее догадка.': 'The host reveals clues to the word one by one. The fewer the hints, the more a correct guess is worth.',
  'Угадывай первым': 'Guess first',
  'Остальные пишут догадки в поле ответа. Кто угадал первым, забирает очки за раунд.': 'Everyone else types guesses in the answer box. Whoever guesses first takes the round’s points.',
  'Меньше подсказок, больше очков': 'Fewer hints, more points',
  'За раннюю догадку очки получают и угадавший, и ведущий. Тяните с подсказками с умом.': 'An early guess scores points for both the guesser and the host. Hold back your hints wisely.',
  'Побеждает счёт': 'Highest score wins',
  'Партия идёт несколько раундов. Кто набрал больше всех очков, тот и победил.': 'A game runs for several rounds. Whoever scores the most points wins.',
  'Боты и друзья': 'Bots and friends',
  'Играй с ботами в одиночку, ищи случайных соперников или зови друзей в комнату по коду.': 'Play solo against bots, find random opponents, or invite friends to a room by code.',
  'Сыграть 🐊': 'Play 🐊',

  // --- Leaderboard.tsx ---
  'Партий': 'Games',
  'Рекорд': 'Best streak',
  'Пока пусто. Сыграй партию, чтобы попасть в таблицу!': 'Empty for now. Play a game to make the board!',

  // --- Stage.tsx ---
  'Выйти': 'Leave',
  'Готовим сцену': 'Setting the stage',
  'Угадал(а) ': 'Guessed by ',
  'Никто не угадал': 'Nobody guessed it',
  'Ты ведущий. Намекай на слово!': 'You’re the host. Hint at the word!',
  'Ведущий: ': 'Host: ',
  'Загаданное слово': 'The secret word',
  'Твоё слово': 'Your word',
  'Угадай слово': 'Guess the word',
  'Раунд ': 'Round ',
  ' из ': ' of ',
  'Открой первую подсказку, чтобы помочь угадать': 'Reveal the first hint to help everyone guess',
  'Ждём первую подсказку от ведущего…': 'Waiting for the host’s first hint…',
  'Подсказка ': 'Hint ',
  'Следующий раунд начнётся через пару секунд': 'The next round starts in a few seconds',
  'Следующая подсказка: «': 'Next hint: “',
  '»': '”',
  'Открыть слово 🐊': 'Reveal the word 🐊',
  'Открыть подсказку': 'Reveal hint',
  'Сдаться': 'Give up',
  'Введи свою догадку…': 'Type your guess…',
  'Отправить': 'Send',

  // --- store.ts toasts / flashes / errors ---
  'Угадал! +': 'Correct! +',
  'Не получилось, попробуй ещё': 'That didn’t work, try again',
  'Не удалось подобрать игру. Проверь связь.': 'Couldn’t find a match. Check your connection.',
  'Не удалось создать комнату. Проверь связь.': 'Couldn’t create a room. Check your connection.',
  'Нет комнаты с таким кодом.': 'No room with that code.',
  'Игра уже началась.': 'The game has already started.',
  'В комнате нет мест.': 'The room is full.',
  'Не удалось войти.': 'Couldn’t join.',
  'Не удалось начать': 'Couldn’t start',

  // --- player labels (store.ts) ---
  'Аня': 'Anna',
  'Боря': 'Bob',
  'Витя': 'Victor',

  // --- word categories (shared/words.ts) ---
  'Животные': 'Animals',
  'Еда': 'Food',
  'Профессии': 'Professions',
  'Природа': 'Nature',
  'Дом': 'Home',
  'Транспорт': 'Transport',
  'Спорт': 'Sports',
  'Сказки': 'Fairy tales',
  'Музыка': 'Music',
  'Школа': 'School',
  'Праздник': 'Holidays',
  'Техника': 'Gadgets',

  // --- words (shared/words.ts) ---
  'Крокодил': 'Crocodile',
  'Жираф': 'Giraffe',
  'Ёжик': 'Hedgehog',
  'Пингвин': 'Penguin',
  'Кенгуру': 'Kangaroo',
  'Сова': 'Owl',
  'Дельфин': 'Dolphin',
  'Бабочка': 'Butterfly',
  'Пельмени': 'Dumplings',
  'Мороженое': 'Ice cream',
  'Борщ': 'Borscht',
  'Пицца': 'Pizza',
  'Арбуз': 'Watermelon',
  'Шоколад': 'Chocolate',
  'Блины': 'Pancakes',
  'Космонавт': 'Astronaut',
  'Врач': 'Doctor',
  'Пожарный': 'Firefighter',
  'Повар': 'Chef',
  'Учитель': 'Teacher',
  'Художник': 'Painter',
  'Радуга': 'Rainbow',
  'Вулкан': 'Volcano',
  'Молния': 'Lightning',
  'Снежинка': 'Snowflake',
  'Водопад': 'Waterfall',
  'Подушка': 'Pillow',
  'Зеркало': 'Mirror',
  'Часы': 'Clock',
  'Чайник': 'Kettle',
  'Холодильник': 'Fridge',
  'Самолёт': 'Airplane',
  'Велосипед': 'Bicycle',
  'Поезд': 'Train',
  'Корабль': 'Ship',
  'Ракета': 'Rocket',
  'Футбол': 'Football',
  'Шахматы': 'Chess',
  'Плавание': 'Swimming',
  'Бокс': 'Boxing',
  'Лыжи': 'Skis',
  'Колобок': 'Kolobok',
  'Золушка': 'Cinderella',
  'Буратино': 'Pinocchio',
  'Русалка': 'Mermaid',
  'Дракон': 'Dragon',
  'Гитара': 'Guitar',
  'Барабан': 'Drum',
  'Пианино': 'Piano',
  'Скрипка': 'Violin',
  'Карандаш': 'Pencil',
  'Глобус': 'Globe',
  'Рюкзак': 'Backpack',
  'Дневник': 'Diary',
  'Ёлка': 'Christmas tree',
  'Торт': 'Cake',
  'Салют': 'Fireworks',
  'Подарок': 'Gift',
  'Снеговик': 'Snowman',
  'Телефон': 'Phone',
  'Робот': 'Robot',
  'Камера': 'Camera',
  'Лампочка': 'Light bulb',
  'дом': 'house',

  // --- hints (shared/words.ts) ---
  // Crocodile
  'Живёт у воды': 'Lives near the water',
  'Очень древний': 'Very ancient',
  'Зелёный и зубастый': 'Green and toothy',
  'Лежит как бревно в реке': 'Lies like a log in the river',
  'Его именем зовут эту игру': 'This game is named after it',
  // Giraffe
  'Живёт в саванне': 'Lives in the savanna',
  'Очень спокойный': 'Very calm',
  'Весь в пятнах': 'Covered in spots',
  'Достаёт листья с верхушки': 'Reaches leaves at the treetops',
  'Самая длинная шея на свете': 'The longest neck in the world',
  // Hedgehog
  'Маленький и лесной': 'Small and lives in the forest',
  'Выходит по ночам': 'Comes out at night',
  'Носит яблоки на спине': 'Carries apples on its back',
  'Сворачивается в клубок': 'Rolls up into a ball',
  'Весь в колючках': 'Covered in spines',
  // Penguin
  'Живёт там, где холодно': 'Lives where it’s cold',
  'Птица, но не летает': 'A bird, but it can’t fly',
  'Ходит вразвалочку': 'Waddles when it walks',
  'Чёрно-белый фрак': 'Wears a black-and-white tuxedo',
  'Скользит на животе по льду': 'Slides on its belly across the ice',
  // Kangaroo
  'Живёт в Австралии': 'Lives in Australia',
  'Передвигается прыжками': 'Moves around by hopping',
  'Сильные задние лапы': 'Strong hind legs',
  'Носит малыша в сумке': 'Carries its baby in a pouch',
  'Чемпион по прыжкам': 'A champion jumper',
  // Owl
  'Живёт в лесу': 'Lives in the forest',
  'Бодрствует ночью': 'Stays awake at night',
  'Огромные круглые глаза': 'Huge round eyes',
  'Крутит головой назад': 'Turns its head around backwards',
  'Символ мудрости': 'A symbol of wisdom',
  // Dolphin
  'Живёт в море': 'Lives in the sea',
  'Очень умный': 'Very clever',
  'Дышит воздухом, но не рыба': 'Breathes air, but isn’t a fish',
  'Выпрыгивает из волн': 'Leaps out of the waves',
  'Помогает тонущим людям': 'Helps drowning people',
  // Butterfly
  'Очень лёгкая': 'Very light',
  'Живёт всего пару недель': 'Lives only a couple of weeks',
  'Сначала была гусеницей': 'It was a caterpillar first',
  'Яркие узорчатые крылья': 'Bright patterned wings',
  'Порхает с цветка на цветок': 'Flutters from flower to flower',
  // Dumplings
  'Их лепят руками': 'They’re shaped by hand',
  'Любят всей семьёй': 'Loved by the whole family',
  'Внутри прячется начинка': 'A filling is hidden inside',
  'Варят в кипятке': 'Boiled in hot water',
  'Едят со сметаной': 'Eaten with sour cream',
  // Ice cream
  'Любимое летом': 'A favorite in summer',
  'Бывает в стаканчике': 'Comes in a cup',
  'Очень холодное': 'Very cold',
  'Тает в руках': 'Melts in your hands',
  'Сладкое и в рожке': 'Sweet and served in a cone',
  // Borscht
  'Горячее блюдо': 'A hot dish',
  'Подают в тарелке': 'Served in a bowl',
  'Ярко-красного цвета': 'Bright red in color',
  'Главный овощ, это свёкла': 'Its main vegetable is beetroot',
  'Едят с ложкой сметаны': 'Eaten with a spoon of sour cream',
  // Pizza
  'Родом из Италии': 'Comes from Italy',
  'Делят на кусочки': 'Divided into slices',
  'Круглая и плоская': 'Round and flat',
  'Сверху много сыра': 'Lots of cheese on top',
  'Режут как торт треугольниками': 'Cut into triangles like a cake',
  // Watermelon
  'Поспевает к концу лета': 'Ripens by the end of summer',
  'Очень большой и тяжёлый': 'Very big and heavy',
  'Снаружи зелёный в полоску': 'Green with stripes on the outside',
  'Внутри красный': 'Red on the inside',
  'Полон чёрных косточек': 'Full of black seeds',
  // Chocolate
  'Любимое лакомство': 'A favorite treat',
  'Делают из бобов какао': 'Made from cocoa beans',
  'Бывает горьким и молочным': 'Can be dark or milk',
  'Тает во рту': 'Melts in your mouth',
  'Ломается на дольки': 'Breaks into squares',
  // Pancakes
  'Русское блюдо': 'A Russian dish',
  'Главные на Масленицу': 'The star of Maslenitsa',
  'Круглые и тонкие': 'Round and thin',
  'Пекут на сковороде': 'Cooked in a frying pan',
  'Едят с мёдом или икрой': 'Eaten with honey or caviar',
  // Astronaut
  'Очень смелый': 'Very brave',
  'Долго тренируется': 'Trains for a long time',
  'Работает в невесомости': 'Works in zero gravity',
  'Носит скафандр': 'Wears a spacesuit',
  'Летает к звёздам на ракете': 'Flies to the stars on a rocket',
  // Doctor
  'Помогает людям': 'Helps people',
  'Носит белый халат': 'Wears a white coat',
  'Слушает, как бьётся сердце': 'Listens to your heartbeat',
  'Выписывает лекарства': 'Prescribes medicine',
  'Лечит больных': 'Heals the sick',
  // Firefighter
  'Очень храбрый': 'Very courageous',
  'Приезжает по тревоге': 'Rushes out on an alarm',
  'Носит каску': 'Wears a helmet',
  'Тушит огонь водой': 'Puts out fire with water',
  'Спасает людей из горящего дома': 'Rescues people from a burning house',
  // Chef
  'Работает на кухне': 'Works in the kitchen',
  'Носит высокий колпак': 'Wears a tall hat',
  'Знает много рецептов': 'Knows many recipes',
  'Готовит еду для гостей': 'Cooks food for guests',
  'Пробует блюдо на вкус': 'Tastes the dish',
  // Teacher
  'Работает в школе': 'Works at a school',
  'Очень терпеливый': 'Very patient',
  'Стоит у доски': 'Stands at the blackboard',
  'Ставит оценки': 'Gives out grades',
  'Учит детей новому': 'Teaches children new things',
  // Painter
  'Творческий человек': 'A creative person',
  'Работает в мастерской': 'Works in a studio',
  'Держит кисть': 'Holds a brush',
  'Смешивает краски': 'Mixes paints',
  'Рисует картины': 'Paints pictures',
  // Rainbow
  'Появляется на небе': 'Appears in the sky',
  'Бывает после дождя': 'Shows up after the rain',
  'Изогнута дугой': 'Curved in an arc',
  'В ней семь цветов': 'It has seven colors',
  'Каждый охотник желает знать…': 'Roy G. Biv…',
  // Volcano
  'Это гора': 'It’s a mountain',
  'Спит много лет': 'Sleeps for many years',
  'Внутри очень горячо': 'Very hot inside',
  'Может проснуться и взорваться': 'Can wake up and erupt',
  'Извергает раскалённую лаву': 'Spews out molten lava',
  // Lightning
  'Бывает в грозу': 'Happens during a thunderstorm',
  'Очень яркая вспышка': 'A very bright flash',
  'Длится миг': 'Lasts only an instant',
  'За ней гремит гром': 'Thunder rumbles after it',
  'Бьёт зигзагом с неба': 'Strikes from the sky in a zigzag',
  // Snowflake
  'Появляется зимой': 'Appears in winter',
  'Очень маленькая и лёгкая': 'Very small and light',
  'Падает с неба': 'Falls from the sky',
  'Тает на ладони': 'Melts on your palm',
  'У каждой свой узор, и все разные': 'Each one has its own pattern, all different',
  // Waterfall
  'Связан с водой': 'Has to do with water',
  'Очень шумный': 'Very loud',
  'Находится в горах': 'Found in the mountains',
  'Вода падает с высоты': 'Water falls from a height',
  'С обрыва летит вниз стеной': 'Plunges down a cliff like a wall',
  // Pillow
  'Есть в каждом доме': 'Found in every home',
  'Мягкая на ощупь': 'Soft to the touch',
  'Лежит на кровати': 'Lies on the bed',
  'На ней спят': 'You sleep on it',
  'Ей можно подраться': 'You can have a fight with it',
  // Mirror
  'Висит на стене': 'Hangs on the wall',
  'Гладкое и блестящее': 'Smooth and shiny',
  'В него смотрятся': 'You look into it',
  'Показывает тебя самого': 'Shows you yourself',
  '«Свет мой, …, скажи»': '“Mirror, mirror on the wall…”',
  // Clock
  'Никогда не стоят на месте': 'Never stands still',
  'У них есть стрелки': 'It has hands',
  'Показывают время': 'Shows the time',
  'Звонят по утрам, чтобы разбудить': 'Rings in the morning to wake you',
  // Kettle
  'Стоит на кухне': 'Sits in the kitchen',
  'У него есть носик и ручка': 'It has a spout and a handle',
  'В него наливают воду': 'You pour water into it',
  'Закипает и свистит': 'Boils and whistles',
  'Из него заваривают чай': 'You brew tea with it',
  // Fridge
  'Большой и белый': 'Big and white',
  'Гудит днём и ночью': 'Hums day and night',
  'Внутри всегда холодно': 'Always cold inside',
  'Хранит продукты свежими': 'Keeps food fresh',
  // Airplane
  'Очень быстрый': 'Very fast',
  'У него есть крылья': 'It has wings',
  'Взлетает с полосы': 'Takes off from a runway',
  'Летит высоко над облаками': 'Flies high above the clouds',
  'Возит людей между странами': 'Carries people between countries',
  // Bicycle
  'Едет по дороге': 'Rides along the road',
  'У него два колеса': 'It has two wheels',
  'Нужно крутить педали': 'You pedal to move it',
  'Держат руль руками': 'You hold the handlebars',
  'Звенит звоночком': 'Rings its little bell',
  // Train
  'Возит много людей': 'Carries lots of people',
  'Едет только по рельсам': 'Runs only on rails',
  'Очень длинный': 'Very long',
  'У него много вагонов': 'It has many carriages',
  'Гудит и стучит колёсами': 'Hoots and clatters its wheels',
  // Ship
  'Большой и тяжёлый': 'Big and heavy',
  'Не тонет, хотя железный': 'Doesn’t sink, even though it’s iron',
  'У него есть капитан': 'It has a captain',
  'Плывёт по морю': 'Sails across the sea',
  'Бросает якорь в порту': 'Drops anchor in the harbor',
  // Rocket
  'Очень быстрая': 'Very fast',
  'Оставляет огненный хвост': 'Leaves a fiery trail',
  'Стартует с космодрома': 'Launches from a spaceport',
  'Летит вверх с грохотом': 'Roars upward',
  'Уносит космонавтов в космос': 'Carries astronauts into space',
  // Football
  'Командная игра': 'A team game',
  'Играют на поле': 'Played on a field',
  'Нужен круглый мяч': 'You need a round ball',
  'Бьют только ногами': 'Played only with your feet',
  'Гол забивают в ворота': 'You score a goal into the net',
  // Chess
  'Игра для двоих': 'A game for two',
  'Нужно много думать': 'Takes a lot of thinking',
  'Доска в клеточку': 'A checkered board',
  'Есть король и королева': 'It has a king and a queen',
  'Цель игры, поставить мат': 'The goal is to checkmate',
  // Swimming
  'Спорт в бассейне': 'A sport done in a pool',
  'Нужны очки и шапочка': 'You need goggles and a cap',
  'Двигают руками и ногами': 'You move your arms and legs',
  'Плывут наперегонки по дорожкам': 'You race along the lanes',
  // Boxing
  'Спорт для смелых': 'A sport for the brave',
  'Бьются один на один': 'Fought one on one',
  'Нужны перчатки': 'You need gloves',
  'Дерутся на ринге': 'Fought in a ring',
  'Побеждает тот, кто устоял': 'Whoever stays standing wins',
  // Skis
  'Зимний спорт': 'A winter sport',
  'Нужен снег': 'You need snow',
  'Держат две палки': 'You hold two poles',
  'Скользят с горы': 'You glide down the hill',
  'Две длинные доски на ногах': 'Two long boards on your feet',
  // Kolobok
  'Герой русской сказки': 'A character from a Russian folk tale',
  'Круглый и румяный': 'Round and rosy',
  'Испекли из теста': 'Baked from dough',
  'Укатился от бабушки и дедушки': 'Rolled away from grandma and grandpa',
  'Его съела хитрая лиса': 'Eaten by a cunning fox',
  // Cinderella
  'Героиня сказки': 'A fairy-tale heroine',
  'Много работала по дому': 'Did lots of housework',
  'У неё злая мачеха': 'She has a wicked stepmother',
  'Потеряла туфельку на балу': 'Lost her slipper at the ball',
  'Уехала в карете из тыквы': 'Rode off in a pumpkin carriage',
  // Pinocchio
  'Герой сказки': 'A fairy-tale character',
  'Сделан из дерева': 'Made of wood',
  'Папа Карло вырезал его из полена': 'Carved from a log by Papa Carlo',
  'У него длинный нос': 'He has a long nose',
  'Нашёл золотой ключик': 'Found a golden key',
  // Mermaid
  'Сказочное существо': 'A fairy-tale creature',
  'Живёт в воде': 'Lives in the water',
  'Наполовину человек': 'Half human',
  'Вместо ног рыбий хвост': 'Has a fish tail instead of legs',
  'Сидит на камне и поёт': 'Sits on a rock and sings',
  // Dragon ('У него есть крылья' / 'It has wings' already defined above for Airplane)
  'Сказочное чудище': 'A mythical monster',
  'Огромный и страшный': 'Huge and scary',
  'Бывает о трёх головах': 'Sometimes has three heads',
  'Дышит огнём': 'Breathes fire',
  // Guitar
  'Музыкальный инструмент': 'A musical instrument',
  'У неё есть струны': 'It has strings',
  'Её берут на руки': 'You hold it in your arms',
  'Под неё поют у костра': 'People sing along to it by the campfire',
  // Drum
  'Очень громкий': 'Very loud',
  'По нему бьют палочками': 'You hit it with sticks',
  'Задаёт ритм': 'Sets the rhythm',
  'Бум-бум-бум': 'Boom-boom-boom',
  // Piano
  'Большое и тяжёлое': 'Big and heavy',
  'Чёрно-белые клавиши': 'Black-and-white keys',
  'На нём играют двумя руками': 'Played with both hands',
  'Стоит в концертном зале': 'Stands in a concert hall',
  // Violin
  'Небольшая и изящная': 'Small and elegant',
  'У неё четыре струны': 'It has four strings',
  'Играют смычком': 'Played with a bow',
  'Держат у подбородка': 'Held under the chin',
  // Pencil
  'Лежит в пенале': 'Kept in a pencil case',
  'Деревянный и длинный': 'Wooden and long',
  'Им пишут и рисуют': 'You write and draw with it',
  'Можно стереть резинкой': 'Can be erased with a rubber',
  'Его точат точилкой': 'Sharpened with a sharpener',
  // Globe
  'Стоит в классе географии': 'Sits in the geography classroom',
  'Круглый, можно крутить': 'Round, and you can spin it',
  'На нём моря и материки': 'It shows seas and continents',
  'Уменьшенная копия Земли': 'A tiny model of the Earth',
  'Крутится на подставке': 'Spins on a stand',
  // Backpack
  'Носят за спиной': 'Worn on your back',
  'У него есть лямки': 'It has straps',
  'Внутри много кармашков': 'Lots of pockets inside',
  'В нём носят учебники': 'You carry textbooks in it',
  'С ним идут в школу': 'You take it to school',
  // Diary
  'Есть у каждого ученика': 'Every pupil has one',
  'Небольшая тетрадь': 'A small notebook',
  'В нём расписание уроков': 'It holds the class timetable',
  'Туда ставят оценки': 'Grades are written in it',
  'Его показывают родителям': 'You show it to your parents',
  // Christmas tree
  'Появляется раз в год': 'Appears once a year',
  'Зелёная и колючая': 'Green and prickly',
  'Её наряжают игрушками': 'Decorated with ornaments',
  'Под ней лежат подарки': 'Presents lie beneath it',
  'Главный символ Нового года': 'The main symbol of the New Year',
  // Cake
  'Бывает на празднике': 'Shows up at a celebration',
  'Очень сладкий': 'Very sweet',
  'Сверху крем и украшения': 'Frosting and decorations on top',
  'В него втыкают свечи': 'Candles are stuck into it',
  'Его задувают и загадывают желание': 'You blow them out and make a wish',
  // Fireworks
  'Бывает по праздникам': 'Set off on holidays',
  'Его видно только в темноте': 'Only visible in the dark',
  'Взлетает в небо': 'Shoots up into the sky',
  'Рассыпается яркими огнями': 'Bursts into bright lights',
  // Gift
  'Любят и дети, и взрослые': 'Loved by children and grown-ups alike',
  'Его дарят на праздник': 'Given on a special occasion',
  'Завёрнут в красивую бумагу': 'Wrapped in pretty paper',
  'Перевязан бантом': 'Tied with a bow',
  'Интересно, что внутри': 'You wonder what’s inside',
  // Snowman
  'Его лепят из снега': 'Built out of snow',
  'Стоит во дворе': 'Stands in the yard',
  'Вместо носа морковка': 'A carrot for a nose',
  'Три снежных кома друг на друге': 'Three snowballs stacked on top of each other',
  // Phone
  'Есть почти у каждого': 'Almost everyone has one',
  'Помещается в кармане': 'Fits in your pocket',
  'Светится экраном': 'Glows with a screen',
  'По нему звонят и пишут': 'You call and text with it',
  'В нём живут все приложения': 'All the apps live inside it',
  // Robot
  'Его придумали люди': 'Invented by people',
  'Сделан из металла': 'Made of metal',
  'Работает на батарейках': 'Runs on batteries',
  'Умеет выполнять команды': 'Can carry out commands',
  'Железный помощник из будущего': 'A metal helper from the future',
  // Camera
  'Полезное устройство': 'A handy device',
  'У неё есть объектив': 'It has a lens',
  'Её наводят и щёлкают': 'You aim it and click',
  'Сохраняет важные моменты': 'Captures important moments',
  'Делает фотографии': 'Takes photographs',
  // Light bulb
  'Есть в каждой комнате': 'In every room',
  'Стеклянная и хрупкая': 'Glassy and fragile',
  'Висит под потолком': 'Hangs from the ceiling',
  'Её включают выключателем': 'Turned on with a switch',
  'Светит, когда темно': 'Shines when it’s dark',
}
